# CrateDigger terminal UI — English
PRINT_PROFILE="⚙️  Profile: %s"
PRINT_CONFIG_READ_ERROR="⚠️  Cannot read %s: %s"
PRINT_NO_CONFIG="No .cratediggerrc found; only profile 'default' is available."
PRINT_HOOK_EXECUTING="🔗 Executing %s hook..."
PRINT_HOOK_START_ERROR="⚠️  Could not start %s hook: %s"
PRINT_HOOK_EXIT_ERROR="⚠️  %s hook exited with code %s."
PRINT_LOADING_AUDIO="Loading audio..."
PRINT_QUERY_SHAZAM="Querying Shazam..."
PRINT_TIMEOUT="❌ Network timeout while connecting to Shazam."
PRINT_CONNECTION_ERROR="❌ Cannot connect to Shazam (%s)."
PRINT_NETWORK_DISCONNECTED="❌ Network connection lost."
PRINT_HTTP_ERROR="❌ HTTP error %s from Shazam."
PRINT_DNS_ERROR="❌ DNS lookup failed."
PRINT_NETWORK_ERROR="❌ Network error: %s"
PRINT_UNEXPECTED_ERROR="❌ Unexpected error during recognition: %s"
PRINT_FOUND="✅ Track found"
PRINT_TITLE="Title   : %s"
PRINT_ARTIST="Artist  : %s"
PRINT_GENRE="Genre   : %s"
PRINT_MATCH="Match   : %g"
PRINT_YEAR="Year    : %s"
PRINT_ALBUM="Album   : %s"
PRINT_SOURCE="Source  : %s"
PRINT_NO_MATCH="❌ No match."
PRINT_FRAGMENT_SAVED="🎧 Fragment saved: file://%s"
PRINT_FRAGMENT_SAVED_PLAIN="Fragment saved: %s"
PRINT_PAUSE_HINT="Press 'p' to pause/resume."
PRINT_QUIT="\n⏹ Quit requested"
PRINT_RESET="\n↻ Reset — new recording from 0s"
PRINT_CONTINUED="\n▶ Continued"
PRINT_PAUSED="\n⏸ Paused — press 'p' to continue"
PRINT_LISTENING="Listening via %s (%ss)..."
PRINT_SILENCE="⚠️  Captured audio contains only silence (all samples are zero) — Shazam will not be queried."
PRINT_SILENT_FRAGMENT_SAVED="🎧 Silent fragment saved: file://%s"
PRINT_NEXT_RECORDING="Next recording in %ss..."
PRINT_DELAY="Delay after matched track: %ss..."
PRINT_NO_MEDIA="No supported media files found."
PRINT_FILE_PROGRESS="\n[%s/%s] %s"
PRINT_WATCHING="👀 Watching: %s"
PRINT_STOP_HINT="Ctrl-C to stop."
PRINT_NEW_FILE="\n📁 New file: %s"
PRINT_DEBUG_FRAGMENT="Debug fragment saved: %s"
PRINT_FRAGMENT_KEPT="Fragment kept: %s"

PRINT_HOOKS_DEFAULTS = "[HOOKS] DEFAULTS"
PRINT_HOOK_HEADER = "HOOK"
PRINT_COMMAND_HEADER = "COMMAND"
PRINT_FEATURE_HEADER = "FEATURE"
PRINT_HOOK_DEDUPE = "🔗 afterfound hook skipped: same track as previous recognition."

PRINT_INVALID_TIME = "Ongeldige tijd. Gebruik seconden, MM:SS of UU:MM:SS."
PRINT_INVALID_TIME_URL = "Ongeldige tijd in de url: %s"
PRINT_START_AFTER_END = "Starttijd ligt voorbij het einde van de file."
PRINT_CUT_FRAGMENT = "Fragment %s (%ss) uitsnijden..."
PRINT_YTDLP_NOT_INSTALLED = "yt-dlp is niet geïnstalleerd (nodig voor YouTube-url's)."
PRINT_AUDIO_DOWNLOAD_RANGE = "Audio ophalen van %.1fs tot %.1fs..."
PRINT_UNKNOWN_ERROR = "onbekende fout"
PRINT_YTDLP_DOWNLOAD_ERROR = "yt-dlp kon het gedeelte niet ophalen: %s"
PRINT_YTDLP_NO_AUDIO = "yt-dlp leverde geen audiobestand op."
PRINT_YTDLP_NO_USABLE_SECTION = (
    "yt-dlp leverde geen bruikbaar gedeelte op "
    "(mogelijk voorbij het einde van de video)."
)
PRINT_WAV_CONVERSION_ERROR = "Audio kon niet naar WAV worden omgezet: %s"
PRINT_FFMPEG_NOT_INSTALLED = "FFmpeg is niet geïnstalleerd (nodig voor live audio)."
PRINT_UNKNOWN_LIVE_INPUT = "Onbekende live-input: %s"
PRINT_LIVE_RECORD_ERROR = "%s audio kon niet worden opgenomen van '%s': %s"
PRINT_LIVE_RECORD_ERROR_PLAIN = "%s audio kon niet worden opgenomen van '%s'."
PRINT_RECORDING_METER = "\rRecording sec %2d/%d  [%s] %s  peak %s dBFS"
PRINT_METADATA_FIELD = "%-8s: %s"
PRINT_DEBUG_FIELD = "%-12s: %s"
PRINT_ERROR = "❌ %s"
PRINT_INTERVAL_NEGATIVE = "--interval mag niet negatief zijn."
PRINT_DURATION_INVALID = "--duration moet groter zijn dan 0."
PRINT_DELAY_NEGATIVE = "--delay mag niet negatief zijn."
PRINT_DIRECTORY_NOT_FOUND = "❌ Directory niet gevonden: %s"
PRINT_RECURSIVE_REQUIRES_DIRECTORY = "--recursive vereist een directory"
PRINT_RECURSIVE_LOCAL_ONLY = "--recursive werkt alleen met lokale directories"
PRINT_INVALID_START_TIME = "Ongeldige starttijd: %s"
PRINT_MEDIA_REQUIRED = "geef een mediafile/url op, of gebruik --live"
PRINT_YTDLP_NOT_INSTALLED_SHORT = "yt-dlp is niet geïnstalleerd."
PRINT_AUDIO_DOWNLOAD = "Audio ophalen van %s"
PRINT_DOWNLOAD_FAILED = "Ophalen mislukt: %s"
PRINT_AUDIO_SAVED = "Audio bewaard: %s"
PRINT_FILE_NOT_FOUND = "❌ Bestand niet gevonden: %s"
PRINT_INTERRUPTED = "\nAfgebroken."
ERROR_NETWORK_TIMEOUT = "Netwerk-timeout tijdens verbinden met Shazam."
ERROR_CONNECTION = "Kan geen verbinding maken met Shazam (%s)."
ERROR_NETWORK_DISCONNECTED = "Netwerkverbinding verbroken."
ERROR_HTTP = "HTTP-fout %s van Shazam."
ERROR_DNS = "DNS lookup mislukt."
ERROR_NETWORK = "Netwerkfout: %s"

CLI_DESCRIPTION = "Herken een fragment uit een mediafile met Shazam."
CLI_HELP_PROFILE = "Gebruik een profiel uit .cratediggerrc (default: default)"
CLI_HELP_LIST_PROFILES = "Toon alle profielen en hun effectieve instellingen in tabelvorm"
CLI_HELP_LIVE = "Luister naar live audio via ALSA in plaats van een bestand/url"
CLI_HELP_INTERVAL = "Wachttijd in seconden tussen live-opnames (default: 5)"
CLI_HELP_DELAY = "Wachttijd in seconden na een gevonden nummer (default: 0)"
CLI_HELP_INPUT = "Live audio backend: alsa, pulse of jack (default: alsa)"
CLI_HELP_DEVICE = "Input device/source/client (default: default)"
CLI_HELP_LOOP = "Blijf live audio opnemen en herkennen"
CLI_HELP_RECURSIVE = "Verwerk alle ondersteunde mediafiles in een directory, inclusief subdirectories"
CLI_HELP_WATCH = "Blijf een directory bewaken en herken nieuw toegevoegde/gewijzigde mediafiles"
CLI_HELP_MEDIAFILE = (
    "Pad naar media-bestand, of een HTTP(S)-url die yt-dlp ondersteunt "
    "(bv. YouTube, SoundCloud of Bandcamp)."
)
CLI_HELP_TIME = (
    "Starttijd. "
    "Voorbeelden: "
    "65 (seconden), "
    "10:03 (MM:SS), "
    "1:10:03 (UU:MM:SS). "
    "Default: de tijd uit de url, anders 0."
)
CLI_HELP_DURATION = "Fragmentduur in seconden (default: 25)"
CLI_HELP_JSON = "JSON-output"
CLI_HELP_KEEP_TEMP = (
    "Bewaar tijdelijk fragment "
    "(bij een url ook het gedownloade audiobestand)."
)
CLI_HELP_DEBUG = "Bewaar live-opnames in /tmp in plaats van ze na herkenning te verwijderen"
