# CrateDigger terminal UI — Français
PRINT_PROFILE="⚙️  Profil : %s"
PRINT_CONFIG_READ_ERROR="⚠️  Impossible de lire %s : %s"
PRINT_NO_CONFIG="Aucun .cratediggerrc trouvé ; seul le profil 'default' est disponible."
PRINT_HOOK_EXECUTING="🔗 Exécution du hook %s..."
PRINT_HOOK_START_ERROR="⚠️  Impossible de démarrer le hook %s : %s"
PRINT_HOOK_EXIT_ERROR="⚠️  Le hook %s s'est terminé avec le code %s."
PRINT_LOADING_AUDIO="Chargement de l'audio..."
PRINT_QUERY_SHAZAM="Interrogation de Shazam..."
PRINT_TIMEOUT="❌ Délai d'attente réseau dépassé lors de la connexion à Shazam."
PRINT_CONNECTION_ERROR="❌ Impossible de se connecter à Shazam (%s)."
PRINT_NETWORK_DISCONNECTED="❌ Connexion réseau interrompue."
PRINT_HTTP_ERROR="❌ Erreur HTTP %s de Shazam."
PRINT_DNS_ERROR="❌ Échec de la résolution DNS."
PRINT_NETWORK_ERROR="❌ Erreur réseau : %s"
PRINT_UNEXPECTED_ERROR="❌ Erreur inattendue pendant la reconnaissance : %s"
PRINT_FOUND="✅ Morceau trouvé"
PRINT_TITLE="Titre   : %s"
PRINT_ARTIST="Artiste : %s"
PRINT_GENRE="Genre   : %s"
PRINT_MATCH="Correspondance : %g"
PRINT_YEAR="Année   : %s"
PRINT_ALBUM="Album   : %s"
PRINT_SOURCE="Source  : %s"
PRINT_NO_MATCH="❌ Aucune correspondance."
PRINT_FRAGMENT_SAVED="🎧 Fragment enregistré : file://%s"
PRINT_FRAGMENT_SAVED_PLAIN="Fragment enregistré : %s"
PRINT_PAUSE_HINT="Appuyez sur 'p' pour mettre en pause/reprendre."
PRINT_QUIT="\n⏹ Arrêt demandé"
PRINT_RESET="\n↻ Réinitialisation — nouvel enregistrement à partir de 0s"
PRINT_CONTINUED="\n▶ Reprise"
PRINT_PAUSED="\n⏸ En pause — appuyez sur 'p' pour continuer"
PRINT_LISTENING="Écoute via %s (%ss)..."
PRINT_SILENCE="⚠️  L'audio capturé ne contient que du silence (tous les échantillons sont nuls) — Shazam ne sera pas interrogé."
PRINT_SILENT_FRAGMENT_SAVED="🎧 Fragment silencieux enregistré : file://%s"
PRINT_NEXT_RECORDING="Prochain enregistrement dans %ss..."
PRINT_DELAY="Délai après un morceau trouvé : %ss..."
PRINT_NO_MEDIA="Aucun fichier multimédia pris en charge trouvé."
PRINT_FILE_PROGRESS="\n[%s/%s] %s"
PRINT_WATCHING="👀 Surveillance : %s"
PRINT_STOP_HINT="Ctrl-C pour arrêter."
PRINT_NEW_FILE="\n📁 Nouveau fichier : %s"
PRINT_DEBUG_FRAGMENT="Fragment de débogage enregistré : %s"
PRINT_FRAGMENT_KEPT="Fragment conservé : %s"

PRINT_HOOKS_DEFAULTS = "[HOOKS] DEFAULTS"
PRINT_HOOK_HEADER = "HOOK"
PRINT_COMMAND_HEADER = "COMMAND"
PRINT_FEATURE_HEADER = "FEATURE"
PRINT_HOOK_DEDUPE = "🔗 afterfound hook overgeslagen: hetzelfde nummer als vorige herkenning."

PRINT_INVALID_TIME = "Ongeldige tijd. Gebruik seconden, MM:SS of UU:MM:SS."
PRINT_INVALID_TIME_URL = "Ongeldige tijd in de url: %s"
PRINT_START_AFTER_END = "Starttijd ligt voorbij het einde van de file."
PRINT_CUT_FRAGMENT = "Fragment %s (%ss) uitsnijden..."
PRINT_YTDLP_NOT_INSTALLED = "yt-dlp is niet geïnstalleerd (nodig voor YouTube-url's)."
PRINT_AUDIO_DOWNLOAD_RANGE = "Audio ophalen van %.1fs tot %.1fs..."
PRINT_UNKNOWN_ERROR = "onbekende fout"
PRINT_YTDLP_DOWNLOAD_ERROR = "yt-dlp kon het gedeelte niet ophalen: %s"
PRINT_YTDLP_NO_AUDIO = "yt-dlp leverde geen audiobestand op."
PRINT_YTDLP_NO_USABLE_SECTION = (
    "yt-dlp leverde geen bruikbaar gedeelte op "
    "(mogelijk voorbij het einde van de video)."
)
PRINT_WAV_CONVERSION_ERROR = "Audio kon niet naar WAV worden omgezet: %s"
PRINT_FFMPEG_NOT_INSTALLED = "FFmpeg is niet geïnstalleerd (nodig voor live audio)."
PRINT_UNKNOWN_LIVE_INPUT = "Onbekende live-input: %s"
PRINT_LIVE_RECORD_ERROR = "%s audio kon niet worden opgenomen van '%s': %s"
PRINT_LIVE_RECORD_ERROR_PLAIN = "%s audio kon niet worden opgenomen van '%s'."
PRINT_RECORDING_METER = "\rRecording sec %2d/%d  [%s] %s  peak %s dBFS"
PRINT_METADATA_FIELD = "%-8s: %s"
PRINT_DEBUG_FIELD = "%-12s: %s"
PRINT_ERROR = "❌ %s"
PRINT_INTERVAL_NEGATIVE = "--interval mag niet negatief zijn."
PRINT_DURATION_INVALID = "--duration moet groter zijn dan 0."
PRINT_DELAY_NEGATIVE = "--delay mag niet negatief zijn."
PRINT_DIRECTORY_NOT_FOUND = "❌ Directory niet gevonden: %s"
PRINT_RECURSIVE_REQUIRES_DIRECTORY = "--recursive vereist een directory"
PRINT_RECURSIVE_LOCAL_ONLY = "--recursive werkt alleen met lokale directories"
PRINT_INVALID_START_TIME = "Ongeldige starttijd: %s"
PRINT_MEDIA_REQUIRED = "geef een mediafile/url op, of gebruik --live"
PRINT_YTDLP_NOT_INSTALLED_SHORT = "yt-dlp is niet geïnstalleerd."
PRINT_AUDIO_DOWNLOAD = "Audio ophalen van %s"
PRINT_DOWNLOAD_FAILED = "Ophalen mislukt: %s"
PRINT_AUDIO_SAVED = "Audio bewaard: %s"
PRINT_FILE_NOT_FOUND = "❌ Bestand niet gevonden: %s"
PRINT_INTERRUPTED = "\nAfgebroken."
ERROR_NETWORK_TIMEOUT = "Netwerk-timeout tijdens verbinden met Shazam."
ERROR_CONNECTION = "Kan geen verbinding maken met Shazam (%s)."
ERROR_NETWORK_DISCONNECTED = "Netwerkverbinding verbroken."
ERROR_HTTP = "HTTP-fout %s van Shazam."
ERROR_DNS = "DNS lookup mislukt."
ERROR_NETWORK = "Netwerkfout: %s"

CLI_DESCRIPTION = "Herken een fragment uit een mediafile met Shazam."
CLI_HELP_PROFILE = "Gebruik een profiel uit .cratediggerrc (default: default)"
CLI_HELP_LIST_PROFILES = "Toon alle profielen en hun effectieve instellingen in tabelvorm"
CLI_HELP_LIVE = "Luister naar live audio via ALSA in plaats van een bestand/url"
CLI_HELP_INTERVAL = "Wachttijd in seconden tussen live-opnames (default: 5)"
CLI_HELP_DELAY = "Wachttijd in seconden na een gevonden nummer (default: 0)"
CLI_HELP_INPUT = "Live audio backend: alsa, pulse of jack (default: alsa)"
CLI_HELP_DEVICE = "Input device/source/client (default: default)"
CLI_HELP_LOOP = "Blijf live audio opnemen en herkennen"
CLI_HELP_RECURSIVE = "Verwerk alle ondersteunde mediafiles in een directory, inclusief subdirectories"
CLI_HELP_WATCH = "Blijf een directory bewaken en herken nieuw toegevoegde/gewijzigde mediafiles"
CLI_HELP_MEDIAFILE = (
    "Pad naar media-bestand, of een HTTP(S)-url die yt-dlp ondersteunt "
    "(bv. YouTube, SoundCloud of Bandcamp)."
)
CLI_HELP_TIME = (
    "Starttijd. "
    "Voorbeelden: "
    "65 (seconden), "
    "10:03 (MM:SS), "
    "1:10:03 (UU:MM:SS). "
    "Default: de tijd uit de url, anders 0."
)
CLI_HELP_DURATION = "Fragmentduur in seconden (default: 25)"
CLI_HELP_JSON = "JSON-output"
CLI_HELP_KEEP_TEMP = (
    "Bewaar tijdelijk fragment "
    "(bij een url ook het gedownloade audiobestand)."
)
CLI_HELP_DEBUG = "Bewaar live-opnames in /tmp in plaats van ze na herkenning te verwijderen"
