# CrateDigger terminal UI — Polski
PRINT_PROFILE="⚙️  Profil: %s"
PRINT_CONFIG_READ_ERROR="⚠️  Nie można odczytać %s: %s"
PRINT_NO_CONFIG="Nie znaleziono pliku .cratediggerrc; dostępny jest tylko profil 'default'."
PRINT_HOOK_EXECUTING="🔗 Uruchamianie hooka %s..."
PRINT_HOOK_START_ERROR="⚠️  Nie można uruchomić hooka %s: %s"
PRINT_HOOK_EXIT_ERROR="⚠️  Hook %s zakończył działanie z kodem %s."
PRINT_LOADING_AUDIO="Wczytywanie audio..."
PRINT_QUERY_SHAZAM="Odpytywanie Shazam..."
PRINT_TIMEOUT="❌ Przekroczono limit czasu sieci podczas łączenia z Shazam."
PRINT_CONNECTION_ERROR="❌ Nie można połączyć się z Shazam (%s)."
PRINT_NETWORK_DISCONNECTED="❌ Połączenie sieciowe zostało przerwane."
PRINT_HTTP_ERROR="❌ Błąd HTTP %s z Shazam."
PRINT_DNS_ERROR="❌ Wyszukiwanie DNS nie powiodło się."
PRINT_NETWORK_ERROR="❌ Błąd sieci: %s"
PRINT_UNEXPECTED_ERROR="❌ Nieoczekiwany błąd podczas rozpoznawania: %s"
PRINT_FOUND="✅ Znaleziono utwór"
PRINT_TITLE="Tytuł   : %s"
PRINT_ARTIST="Artysta : %s"
PRINT_GENRE="Gatunek : %s"
PRINT_MATCH="Dopasowanie: %g"
PRINT_YEAR="Rok     : %s"
PRINT_ALBUM="Album   : %s"
PRINT_SOURCE="Źródło   : %s"
PRINT_NO_MATCH="❌ Brak dopasowania."
PRINT_FRAGMENT_SAVED="🎧 Fragment zapisano: file://%s"
PRINT_FRAGMENT_SAVED_PLAIN="Fragment zapisano: %s"
PRINT_PAUSE_HINT="Naciśnij 'p', aby wstrzymać/wznowić."
PRINT_QUIT="\n⏹ Zażądano zakończenia"
PRINT_RESET="\n↻ Reset — nowe nagranie od 0s"
PRINT_CONTINUED="\n▶ Wznowiono"
PRINT_PAUSED="\n⏸ Wstrzymano — naciśnij 'p', aby kontynuować"
PRINT_LISTENING="Nasłuchiwanie przez %s (%ss)..."
PRINT_SILENCE="⚠️  Przechwycony dźwięk zawiera wyłącznie ciszę (wszystkie próbki są zerowe) — Shazam nie zostanie odpytany."
PRINT_SILENT_FRAGMENT_SAVED="🎧 Cichy fragment zapisano: file://%s"
PRINT_NEXT_RECORDING="Następne nagranie za %ss..."
PRINT_DELAY="Opóźnienie po znalezionym utworze: %ss..."
PRINT_NO_MEDIA="Nie znaleziono obsługiwanych plików multimedialnych."
PRINT_FILE_PROGRESS="\n[%s/%s] %s"
PRINT_WATCHING="👀 Monitorowanie: %s"
PRINT_STOP_HINT="Ctrl-C, aby zatrzymać."
PRINT_NEW_FILE="\n📁 Nowy plik: %s"
PRINT_DEBUG_FRAGMENT="Fragment debugowania zapisano: %s"
PRINT_FRAGMENT_KEPT="Fragment zachowano: %s"

PRINT_HOOKS_DEFAULTS = "[HOOKS] DEFAULTS"
PRINT_HOOK_HEADER = "HOOK"
PRINT_COMMAND_HEADER = "COMMAND"
PRINT_FEATURE_HEADER = "FEATURE"
PRINT_HOOK_DEDUPE = "🔗 afterfound hook overgeslagen: hetzelfde nummer als vorige herkenning."

PRINT_INVALID_TIME = "Ongeldige tijd. Gebruik seconden, MM:SS of UU:MM:SS."
PRINT_INVALID_TIME_URL = "Ongeldige tijd in de url: %s"
PRINT_START_AFTER_END = "Starttijd ligt voorbij het einde van de file."
PRINT_CUT_FRAGMENT = "Fragment %s (%ss) uitsnijden..."
PRINT_YTDLP_NOT_INSTALLED = "yt-dlp is niet geïnstalleerd (nodig voor YouTube-url's)."
PRINT_AUDIO_DOWNLOAD_RANGE = "Audio ophalen van %.1fs tot %.1fs..."
PRINT_UNKNOWN_ERROR = "onbekende fout"
PRINT_YTDLP_DOWNLOAD_ERROR = "yt-dlp kon het gedeelte niet ophalen: %s"
PRINT_YTDLP_NO_AUDIO = "yt-dlp leverde geen audiobestand op."
PRINT_YTDLP_NO_USABLE_SECTION = (
    "yt-dlp leverde geen bruikbaar gedeelte op "
    "(mogelijk voorbij het einde van de video)."
)
PRINT_WAV_CONVERSION_ERROR = "Audio kon niet naar WAV worden omgezet: %s"
PRINT_FFMPEG_NOT_INSTALLED = "FFmpeg is niet geïnstalleerd (nodig voor live audio)."
PRINT_UNKNOWN_LIVE_INPUT = "Onbekende live-input: %s"
PRINT_LIVE_RECORD_ERROR = "%s audio kon niet worden opgenomen van '%s': %s"
PRINT_LIVE_RECORD_ERROR_PLAIN = "%s audio kon niet worden opgenomen van '%s'."
PRINT_RECORDING_METER = "\rRecording sec %2d/%d  [%s] %s  peak %s dBFS"
PRINT_METADATA_FIELD = "%-8s: %s"
PRINT_DEBUG_FIELD = "%-12s: %s"
PRINT_ERROR = "❌ %s"
PRINT_INTERVAL_NEGATIVE = "--interval mag niet negatief zijn."
PRINT_DURATION_INVALID = "--duration moet groter zijn dan 0."
PRINT_DELAY_NEGATIVE = "--delay mag niet negatief zijn."
PRINT_DIRECTORY_NOT_FOUND = "❌ Directory niet gevonden: %s"
PRINT_RECURSIVE_REQUIRES_DIRECTORY = "--recursive vereist een directory"
PRINT_RECURSIVE_LOCAL_ONLY = "--recursive werkt alleen met lokale directories"
PRINT_INVALID_START_TIME = "Ongeldige starttijd: %s"
PRINT_MEDIA_REQUIRED = "geef een mediafile/url op, of gebruik --live"
PRINT_YTDLP_NOT_INSTALLED_SHORT = "yt-dlp is niet geïnstalleerd."
PRINT_AUDIO_DOWNLOAD = "Audio ophalen van %s"
PRINT_DOWNLOAD_FAILED = "Ophalen mislukt: %s"
PRINT_AUDIO_SAVED = "Audio bewaard: %s"
PRINT_FILE_NOT_FOUND = "❌ Bestand niet gevonden: %s"
PRINT_INTERRUPTED = "\nAfgebroken."
ERROR_NETWORK_TIMEOUT = "Netwerk-timeout tijdens verbinden met Shazam."
ERROR_CONNECTION = "Kan geen verbinding maken met Shazam (%s)."
ERROR_NETWORK_DISCONNECTED = "Netwerkverbinding verbroken."
ERROR_HTTP = "HTTP-fout %s van Shazam."
ERROR_DNS = "DNS lookup mislukt."
ERROR_NETWORK = "Netwerkfout: %s"

CLI_DESCRIPTION = "Herken een fragment uit een mediafile met Shazam."
CLI_HELP_PROFILE = "Gebruik een profiel uit .cratediggerrc (default: default)"
CLI_HELP_LIST_PROFILES = "Toon alle profielen en hun effectieve instellingen in tabelvorm"
CLI_HELP_LIVE = "Luister naar live audio via ALSA in plaats van een bestand/url"
CLI_HELP_INTERVAL = "Wachttijd in seconden tussen live-opnames (default: 5)"
CLI_HELP_DELAY = "Wachttijd in seconden na een gevonden nummer (default: 0)"
CLI_HELP_INPUT = "Live audio backend: alsa, pulse of jack (default: alsa)"
CLI_HELP_DEVICE = "Input device/source/client (default: default)"
CLI_HELP_LOOP = "Blijf live audio opnemen en herkennen"
CLI_HELP_RECURSIVE = "Verwerk alle ondersteunde mediafiles in een directory, inclusief subdirectories"
CLI_HELP_WATCH = "Blijf een directory bewaken en herken nieuw toegevoegde/gewijzigde mediafiles"
CLI_HELP_MEDIAFILE = (
    "Pad naar media-bestand, of een HTTP(S)-url die yt-dlp ondersteunt "
    "(bv. YouTube, SoundCloud of Bandcamp)."
)
CLI_HELP_TIME = (
    "Starttijd. "
    "Voorbeelden: "
    "65 (seconden), "
    "10:03 (MM:SS), "
    "1:10:03 (UU:MM:SS). "
    "Default: de tijd uit de url, anders 0."
)
CLI_HELP_DURATION = "Fragmentduur in seconden (default: 25)"
CLI_HELP_JSON = "JSON-output"
CLI_HELP_KEEP_TEMP = (
    "Bewaar tijdelijk fragment "
    "(bij een url ook het gedownloade audiobestand)."
)
CLI_HELP_DEBUG = "Bewaar live-opnames in /tmp in plaats van ze na herkenning te verwijderen"
